### Update an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Jaribu Sasa Update 1",
  "email": "sasa_Update_1@gmail.com",
  "address": "123 Main St, Anytown, USA",
  "dateOfBirth": "1993-05-15"
}

###